export const UPDATE_ABOUT = "UPDATE_ABOUT";
export const UPDATE_SKILLS = "UPDATE_SKILLS";
export const UPDATE_PORTFOLIO = "UPDATE_PORTFOLIO";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const UPDATE_CONTACT = "UPDATE_CONTACT";